#!/bin/bash

cdialog () {
  yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

if [[ "$1" == '--shutdown' ]]; then
  # cdia
  if [[ "$?" == 0 ]]; then
    systemctl poweroff
    else
    exit
    fi
elif [[ "$1" == '--reboot' ]]; then
  # cdia
  if [[ "$?" == 0 ]]; then
    systemctl reboot
    else
    exit
    fi
elif [[ "$1" == '--hibernate' ]]; then
  # cdia
  if [[ "$?" == 0 ]]; then
    systemctl hibernate
    else
    exit
    fi
elif [[ "$1" == '--lock' ]]; then
  ~/.config/hypr/scripts/lockscreen
elif [[ "$1" == '--suspend' ]]; then
  # cdia
  if [[ "$?" == 0 ]]; then
    # mpc -q pause
    pamixer -m
    ~/.config/hypr/scripts/lockscreen
    systemctl suspend
    else
    exit
    fi
elif [[ "$1" == '--logout' ]]; then
  # cdia
  if [[ "$?" == 0 ]]; then
    kill -9 -1
    else
    exit
    fi
fi
