#!/bin/bash

# Define directories and files
scriptsDir="$HOME/.config/hypr/scripts"
lock="$scriptsDir/lockscreen"

# Autostart programs
# swayidle -w timeout 300 '$lock' &
# swayidle -w timeout 600 'systemctl suspend' &
swaybg -i "$HOME/Pictures/wallpapers/wallhaven-6kqk77.jpg" -m fill &
udiskie &
/usr/lib/polkit-kde-authentication-agent-1 &
$scriptsDir/status &
blueman-applet &
nm-applet &
mako &
$scriptsDir/gtkthemes &
nextcloud &
./monitor_config_home &
playerctld daemon &

# Exit
exit 0
