#!/bin/bash

# Define directories and files
scriptsDir="$HOME/.config/hypr/scripts"
lock="$scriptsDir/lockscreen"

swaybg -i "$HOME/Pictures/forest-river.jpg" &
sh $scriptsDir/status &
sh $scriptsDir/monitor_config_remote &
blueman-applet &
nm-applet &
mako &
playerctld daemon &
nextcloud-client &

# Exit
exit 0
