require("lars.plugin")
require("lars.remap")
require("lars.set")

require("lars.colors")
require("lars.lualine")
require("lars.autopairs")
require("lars.lsp")
require("lars.telescope")
require("lars.harpoon")
require("lars.fugitive")
require("lars.undotree")
require("lars.treesitter")
require("lars.comment")
