
windowrule = match:class ^(yad|nm-connection-editor|pavucontrol|Rofi|polkit-kde-authentication-agent-1|feh|blueman-manager)$, float on

windowrule = match:class ^Mattermost$, workspace 6 silent
windowrule = match:class ^thunderbird$, workspace 6 silent
windowrule = match:class ^Spotify$, workspace 5 silent
windowrule = match:class ^discord$, workspace 5 silent
windowrule = match:class ^com\\.nextcloud\\.desktopclient\\.nextcloud$, workspace 9 silent
windowrule = match:class ^com\\.cisco\\.anyconnect\\.gui$, workspace 9 silent

windowrule = match:class ^(gksqt)$, float on
windowrule = match:title ^(Figure 1)$, float on
windowrule = match:title ^(Figure 2)$, float on
windowrule = match:title ^(Figure 3)$, float on
windowrule = match:title ^(Figure 4)$, float on
windowrule = match:class ^(zoom)$, float on
windowrule = match:class ^floating$, float on
windowrule = match:title App, float on

windowrule = match:class fully, fullscreen on

# windowrulev2 = opacity 0.9 0.9,class:^(kitty)$
# windowrulev2 = opacity 0.9 0.9,class:^(Alacritty)$
# windowrulev2 = opacity 0.9 0.9,class:^(foot)$
# windowrulev2 = opacity 0.8 0.8,class:^(neovide)$

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = match:float false, match:workspace w[tv1], border_size 0
windowrule = match:float false, match:workspace w[tv1], rounding 0
windowrule = match:float false, match:workspace f[1], border_size 0
windowrule = match:float false, match:workspace f[1], rounding 0

layerrule = match:namespace waybar, blur on

windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on
