#!/usr/bin/env bash

# Prompt the user to enter a file extension
extension=$(echo -e "txt\npdf\njpg\npng\nmp3\nmp4\ngif\nzip\nrar\nhtml\njs\npy\ncpp\njava\nsh\nrs\ntoml\nyml" | rofi-dmenu)

# Find files with the given extension in the home directory and its subdirectories
file=$(fd -e "$extension" -I --hidden . ~/ | rofi-dmenu)

# Open the selected file
xdg-open "$file"
