#!/bin/sh

pipewire > /dev/null 2>&1 &

(
     while [ ! -e $XDG_RUNTIME_DIR/pipewire-0 ]; do sleep 0.1; done
     pipewire-pulse > /dev/null 2>&1 &
     wireplumber > /dev/null 2>&1 &
) &

export PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
export PULSE_COOKIE=$XDG_CONFIG_HOME/pulse/cookie

dbus-update-activation-environment WAYLAND_DISPLAY DISPLAY PULSE_SERVER PULSE_COOKIE

mako &
nm-applet &
blueman-applet &
/usr/lib/polkit-kde-authentication-agent-1 &
nextcloud &
foot --server &
