# Colors (Gruvbox dark)

[font]
size = 12

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[env]
TERM= "xterm-256color"

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
